model: BaseModTransformer
params:
  d_model: 256
  dropout: 0.1
  feature_window: 20
  input_nn_dims:
  - 64
  - 128
  - 256
  num_classes: 2
  num_features: 6
  num_heads: 4
  num_kmers: 4096
  num_layer: 3
  output_nn_dims:
  - 256
  - 128
  - 64
  padding_idx: 0
pattern: CG
extension: 7
max_features: 40
